/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author evert
 */
public class Configuracao extends javax.swing.JFrame {

    /**
     * Creates new form Configuracao
     */
    
    static DadosConfiguracao dadosConfiguracao;
    public static TelaPrincipal telaPrincipal;
    
    public Configuracao() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNumCamadas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNumEpocas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jsErroAceito = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jsTaxaAprendizado = new javax.swing.JSlider();
        btSalvarConfi = new javax.swing.JButton();
        jlErroAceito = new javax.swing.JLabel();
        jlTaxaAprendizado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Nº Camadas Intermediaria");

        tfNumCamadas.setText("10");

        jLabel4.setText("Número de épocas");

        tfNumEpocas.setText("10000");

        jLabel5.setText("Erro aceito");

        jsErroAceito.setBackground(new java.awt.Color(255, 255, 255));
        jsErroAceito.setMajorTickSpacing(25);
        jsErroAceito.setMinorTickSpacing(5);
        jsErroAceito.setPaintLabels(true);
        jsErroAceito.setPaintTicks(true);
        jsErroAceito.setToolTipText("");
        jsErroAceito.setValue(5);
        jsErroAceito.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsErroAceitoStateChanged(evt);
            }
        });

        jLabel6.setText("Taxa de Aprendizado");

        jsTaxaAprendizado.setBackground(new java.awt.Color(255, 255, 255));
        jsTaxaAprendizado.setMajorTickSpacing(5);
        jsTaxaAprendizado.setMaximum(10);
        jsTaxaAprendizado.setMinorTickSpacing(1);
        jsTaxaAprendizado.setPaintLabels(true);
        jsTaxaAprendizado.setPaintTicks(true);
        jsTaxaAprendizado.setSnapToTicks(true);
        jsTaxaAprendizado.setValue(4);
        jsTaxaAprendizado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsTaxaAprendizadoStateChanged(evt);
            }
        });

        btSalvarConfi.setText("Salvar");
        btSalvarConfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarConfiActionPerformed(evt);
            }
        });

        jlErroAceito.setText("Valor atual: 5%");

        jlTaxaAprendizado.setText("Valor atual: 0.4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btSalvarConfi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jsTaxaAprendizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlErroAceito)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfNumEpocas)
                            .addComponent(tfNumCamadas)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTaxaAprendizado)
                            .addComponent(jsErroAceito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumCamadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNumEpocas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlErroAceito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsErroAceito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTaxaAprendizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsTaxaAprendizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btSalvarConfi)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarConfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarConfiActionPerformed
        // TODO add your handling code here:

        if (tfNumCamadas.getText().equals(" ") || tfNumEpocas.getText().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Campos vazios");
        } else {
            dadosConfiguracao = new DadosConfiguracao();
            dadosConfiguracao.setNumCamadas(Integer.parseInt(tfNumCamadas.getText()));
            dadosConfiguracao.setNumEpocas(Integer.parseInt(tfNumEpocas.getText()));
            dadosConfiguracao.setErroAceito(Double.parseDouble(Integer.toString(jsErroAceito.getValue())) / 100);
            dadosConfiguracao.setTaxaAprendizado(Double.parseDouble(Integer.toString(jsTaxaAprendizado.getValue())) / 10);
            
            dadosConfiguracao.getNumCamadas();
            dadosConfiguracao.getNumEpocas();
            dadosConfiguracao.getErroAceito();
            dadosConfiguracao.getTaxaAprendizado();
            
            
            RedeNeural.exportarConf(dadosConfiguracao);
            
            telaPrincipal.treinar();
            
            this.dispose();
        }

    }//GEN-LAST:event_btSalvarConfiActionPerformed

    private void jsErroAceitoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsErroAceitoStateChanged
        // TODO add your handling code here:
        jlErroAceito.setText("Valor atual: " + jsErroAceito.getValue() + "%");
    }//GEN-LAST:event_jsErroAceitoStateChanged

    private void jsTaxaAprendizadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsTaxaAprendizadoStateChanged
        // TODO add your handling code here:
        jlTaxaAprendizado.setText("Valor atual: 0." + jsTaxaAprendizado.getValue());
    }//GEN-LAST:event_jsTaxaAprendizadoStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvarConfi;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlErroAceito;
    private javax.swing.JLabel jlTaxaAprendizado;
    private javax.swing.JSlider jsErroAceito;
    private javax.swing.JSlider jsTaxaAprendizado;
    private javax.swing.JTextField tfNumCamadas;
    private javax.swing.JTextField tfNumEpocas;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/conf.png")));
    }

}
